### ISSUE TITLE
Build for Firefox?

### ISSUE THREAD

**Issue by cloudtracer** [cloudtracer/ThreatPinchLookup#11]
It looks like porting Chrome extensions to Firefox has gotten fairly easy, this might only require a little re-factoring to work. 

I stopped using Firefox a long time ago, is this of any interest to anyone?

**Comment by gd1eh** [comment]
Yes, the possibility to use both would be nice

**Comment by cloudtracer** [comment]
I still dabble with trying to get this working from time to time but its not high on my priorities list at the moment.

**Comment by MasterShonuff** [comment]
+1 for firefox support. Thanks in advance

**Comment by cloudtracer** [comment]
Cool thanks @MasterShonuff, sorry I missed your post and never saw this.

I'm going to prioritize getting a Firefox build working in the next month or so. I'll probably have to start with porting the [ThreatPinch Lite](https://chrome.google.com/webstore/detail/threatpinch-lite/jcjcflihdgdhapkadakfahkplbafobbi) build first, since the current inject code to build the on hover popups relies on some webkit only API's that Firefox doesn't support.  This is really the main blocking issue at this point. The rest is some clean up of files and refactoring the chrome API's to map to the cross browser versions.

I might be able to revert the on hover code to use the old injection method, but it wasn't as robust at determining positions and in some rare cases affecting the current page in negative ways. 

The other possibility is refactoring the current code to work in Firefox. 

One step at a time though, stay tuned.

**Comment by cloudtracer** [comment]
Still pending review but the initial ThreatPinch Lite build for Firefox is available here - https://addons.mozilla.org/en-US/firefox/addon/threatpinch-lite/

**Comment by cloudtracer** [comment]
Full ThreatPinch Lookup build for Firefox is here, https://github.com/cloudtracer/ThreatPinchLookup/raw/master/ThreatPinchLookupFirefox.xpi.

**Comment by cloudtracer** [comment]
Full ThreatPinch Lookup for Firefox is now in the Add-ons https://addons.mozilla.org/en-US/firefox/addon/threatpinch-lookup-for-firefox/

**Comment by wesinator** [comment]
> Full ThreatPinch Lookup for Firefox is now in the Add-ons https://addons.mozilla.org/en-US/firefox/addon/threatpinch-lookup-for-firefox/

@cloudtracer extension is no longer available on AMO
Can you re-add it ?

Thanks,
