### ISSUE TITLE
Possibility of adding ThreatCrowd ?

### ISSUE THREAD

**Issue by benrau87** [cloudtracer/ThreatPinchLookup#28]
First off, loving ThreatPinch! 
And just stumbling through the developer settings, was wondering how difficult it would be to implement ThreatCrowd support. I think their API is very similar to VT...

Thanks!

**Comment by cloudtracer** [comment]
Thanks!

I took a quick run at it, it should have been easy enough to put the requests together.  This is what I came up with:

`  "THREATCROWDIP": {
    "authorizationType": "DEFAULT",
    "dataSchema": {
      "title": {
        "linkTitle": "${PINCH.HOVERITEM}",
        "linkUrl": "https://www.threatcrowd.org/ip.php?ip=${PINCH.HOVERITEM}",
        "mapping": "${PINCH.LINKURL}",
        "order": 0,
        "title": "ThreatCrowd"
      },
      "votes": {
        "mapping": "${PINCH.RESPONSE.votes}",
        "order": 1,
        "title": "votes"
      },
      "domains": {
        "condition": "true",
        "datapath": "RESPONSE.resolutions",
        "mapping": "${PINCH.LOOP.domain}",
        "objectloop": true,
        "order": 2,
        "limit": 5,
        "title": "${PINCH.LOOP.last_resolved}"
      },
      "hashes": {
        "condition": "true",
        "datapath": "RESPONSE.hashes",
        "mapping": "${PINCH.LOOP}",
        "objectloop": true,
        "order": 3,
        "limit": 5,
        "title": "Hash"
      }
    },
    "indicatorExpression": "${(PINCH.RESPONSE.votes < 1) ? ((PINCH.RESPONSE.votes == -1 ) ? 'bad' : 'suspicious') : 'good'}",
    "dataType": "JSON",
    "disabled": false,
    "httpHeaders": "",
    "httpType": "GET",
    "lookupName": "ThreatCrowd IPv4 Lookup",
    "lookupType": "IPV4",
    "iocs": true,
    "lookupUrl": "https://www.threatcrowd.org/searchApi/v2/ip/report/?ip=${PINCH.HOVERITEM}",
    "lookupVariable": "THREATCROWDIP",
    "order": 31,
    "requestGroup": "INTERNET"
  },
  "THREATCROWDMD5": {
    "authorizationType": "DEFAULT",
    "dataSchema": {
      "title": {
        "linkTitle": "${PINCH.HOVERITEM}",
        "linkUrl": "https://www.threatcrowd.org/malware.php?md5=${PINCH.HOVERITEM}",
        "mapping": "${PINCH.LINKURL}",
        "order": 0,
        "title": "ThreatCrowd"
      },
      "ips": {
        "condition": "true",
        "datapath": "RESPONSE.ips",
        "mapping": "${PINCH.LOOP}",
        "objectloop": true,
        "order": 1,
        "limit": 5,
        "title": "IP"
      },
      "domains": {
        "condition": "true",
        "datapath": "RESPONSE.domains",
        "mapping": "${PINCH.LOOP}",
        "objectloop": true,
        "order": 2,
        "limit": 5,
        "title": "FQDN"
      }
    },
    "indicatorExpression": "${(PINCH.RESPONSE.scans.length > 0) ? ((PINCH.RESPONSE.scans.length > 2 ) ? 'bad' : 'suspicious') : 'good'}",
    "dataType": "JSON",
    "disabled": false,
    "httpHeaders": "",
    "httpType": "GET",
    "lookupName": "ThreatCrowd MD5 Lookup",
    "lookupType": "MD5",
    "iocs": true,
    "lookupUrl": "https://www.threatcrowd.org/searchApi/v2/file/report/?resource=${PINCH.HOVERITEM}",
    "lookupVariable": "THREATCROWDMD5",
    "order": 32,
    "requestGroup": "INTERNET"
  },
  "THREATCROWDFQDN": {
    "authorizationType": "DEFAULT",
    "dataSchema": {
      "title": {
        "linkTitle": "${PINCH.HOVERITEM}",
        "linkUrl": "https://www.threatcrowd.org/domain.php?domain=${PINCH.HOVERITEM}",
        "mapping": "${PINCH.LINKURL}",
        "order": 0,
        "title": "ThreatCrowd"
      },
      "resolutions": {
        "condition": "true",
        "datapath": "RESPONSE.resolutions",
        "mapping": "${PINCH.LOOP.ip_address}",
        "objectloop": true,
        "order": 1,
        "limit": 5,
        "title": "${PINCH.LOOP.last_resolved}"
      },
      "hashes": {
        "condition": "true",
        "datapath": "RESPONSE.hashes",
        "mapping": "${PINCH.LOOP}",
        "objectloop": true,
        "order": 2,
        "limit": 5,
        "title": "Hash"
      }
    },
    "indicatorExpression": "${(PINCH.RESPONSE.votes < 1) ? ((PINCH.RESPONSE.votes == -1 ) ? 'bad' : 'suspicious') : 'good'}",
    "dataType": "JSON",
    "disabled": false,
    "httpHeaders": "",
    "httpType": "GET",
    "lookupName": "ThreatCrowd FQDN Lookup",
    "lookupType": "EFQDN",
    "iocs": true,
    "lookupUrl": "https://www.threatcrowd.org/searchApi/v2/domain/report/?domain=${PINCH.HOVERITEM}",
    "lookupVariable": "THREATCROWDFQDN",
    "order": 33,
    "requestGroup": "INTERNET"
  }`

Unfortunately the ThreatCrowd REST API is JSON based, but their HTTP responses set the content type as HTML. First time I've come across this behavior, so just throwing in those configs won't work.

I'll see if I can get a patch out tonight and push the ThreatCrowd configs with it.

**Comment by cloudtracer** [comment]
Added ThreatCrowd API request for IPv4, MD5 and FQDN in version 1.0.50 which is currently pushing to the Chrome Web Store for both ThreatPinch Lookup and ThreatPinch Lite.
