### ISSUE TITLE
"Pinch: [SHA1,SHA2,MD5]" Title is not shown when there are multiple hits 

### ISSUE THREAD

**Issue by gd1eh** [cloudtracer/ThreatPinchLookup#32]
When doing a Pinch on SHA1,SHA2 or MD5 and you get multiple hits there won't be a "Pinch: *ENTERLOOKUPTYPE* with copy box" as shown below.

![image](https://cloud.githubusercontent.com/assets/28444871/25748169/83646f48-31aa-11e7-9e47-262a6434da24.png)

It should be like so:

![image](https://cloud.githubusercontent.com/assets/28444871/25748267/ccd597d8-31aa-11e7-89a5-520c46dc8024.png)

Makes it hard to get data out of the box.

**Comment by cloudtracer** [comment]
Hi gd1eh,

Thanks for reporting this. Can you provide the website or name of application that the header is not visible on?

If not that is okay, we'll be pushing some style updates in the next version that will likely correct this issue as similar behavior has been observed on some sites have !important style settings that override the popovers styles.

**Comment by cloudtracer** [comment]
Should be fixed in V2.0.0 which is releasing now and should be available soon! Please re-open if this is not fixed in 2.0.0
