### ISSUE TITLE
Popup doesn't show up over iframe

### ISSUE THREAD

**Issue by gd1eh** [cloudtracer/ThreatPinchLookup#35]
When opening an iframe in for example OSSIM and then doing a Threapinch lookup by hovering over <enter random lookup type> the threatpinch will show over the initial page (and not over the iframe).

**Comment by cloudtracer** [comment]
Will take a look, is this Alienvaults OSSIM?

**Comment by cloudtracer** [comment]
Can you provide perhaps a screenshot (censored of course if there is information to censor) of the area in OSSIM where you encounter the issue?

**Comment by gd1eh** [comment]
Hi,  yes in this case this would be Alienvault. 
Would prefer not to share that kind of stuff (even censored).  

Open to explain it in more detail through another communication channel.

**Comment by cloudtracer** [comment]
Okay cool, shoot me an email at development@threatpinch.com and we can exchange details.

**Comment by cloudtracer** [comment]
2.0.5 has some fixes for the popover placement which might fix this.

**Comment by gd1eh** [comment]
I have 2.0.5 now and still seem to have this problem.
Mouse on the hash -> Box appears behind the iframe.

[image: Inline image 1]


Regards,
Reinier

**Comment by cloudtracer** [comment]
Screenshot didn't attach for some reason.

**Comment by cloudtracer** [comment]
I've tried upping the z-index in 2.0.6, but I'm not entirely sure if that is the issue.

**Comment by gd1eh** [comment]
It looks to be resolved on this end :) Good job!

**Comment by cloudtracer** [comment]
Perfect!
