### ISSUE TITLE
Make a toggle for auto popup and clickable popup

### ISSUE THREAD

**Issue by gd1eh** [cloudtracer/ThreatPinchLookup#36]
Please also make an option that we can switch between the "having to click" 
![image](https://cloud.githubusercontent.com/assets/28444871/26146204/a054af5c-3aef-11e7-86fb-e32b18c1035f.png) and having the popup pop straight away.

**Comment by cloudtracer** [comment]
Hi gd1eh,

You can change the plugin back to "classicMode" by adding the following attribute to the ThreatPinch settings. "classicMode": true,

![image](https://cloud.githubusercontent.com/assets/13334507/26152104/a72577d8-3ad3-11e7-8470-f1cb25eb4b9e.png)

Some of the options are described here: https://www.peerlyst.com/posts/threatpinch-v2-0-0-released-threatpinch?trk=vendor_dashboard_posts_panel

**Comment by gd1eh** [comment]
Thank you. That works. Good job on the overall improvements! :)

**Comment by cloudtracer** [comment]
Thanks! I had a feeling some people might still want the classic mode :+1:
