### ISSUE TITLE
When doing Threat Lookup on SHA1 SHA2 and Md5 no Copy button

### ISSUE THREAD

**Issue by gd1eh** [cloudtracer/ThreatPinchLookup#37]
Hi, 

When doing a MD5, SHA2 or SHA1 Threatpinch lookup there is no Copy button.

![image](https://cloud.githubusercontent.com/assets/28444871/26160564/dfdff802-3b21-11e7-9b75-440fb59fbf06.png)

**Comment by cloudtracer** [comment]
That sucks. I have an idea for a firmer fix for this issue, will take a stab at it tonight and if that doesn't fix the issue I might need some details on how and where to reproduce this.

**Comment by cloudtracer** [comment]
I pushed out a quick update to try and fix this, which is available in 2.0.4. Try forcing the plugin to update and let me know the results.

**Comment by gd1eh** [comment]
I have tested this multiple times and could not reproduce it. Seems to be fixed! Good job man 👍
