### ISSUE TITLE
Add SHA256 hash lookup support

### ISSUE THREAD

**Issue by LocalhostDemon** [cloudtracer/ThreatPinchLookup#62]
Would love SHA256 Hash lookups!  Or is there a reason why this is not already supported?

**Comment by cloudtracer** [comment]
There are a number for SHA2 (Same as SHA256) look ups already.  Is there a particular integration that is missing it?

**Comment by LocalhostDemon** [comment]
No, I'm an Id10T.  I didn't realize that it covered all six hash functions.

**Comment by cloudtracer** [comment]
No worries :+1:
