### ISSUE TITLE
Cannot save width change to IPV4 lookup

### ISSUE THREAD

**Issue by hookhax** [cloudtracer/ThreatPinchLookup#63]
When I edit the settings for IPV4 lookups, I can successfully change the height of the popup. When I change the width (tried 350), it does not persist.

**Comment by cloudtracer** [comment]
@hookhax Thanks for the report! I can reproduce the issue, it looks like the width gets reset to the defaults on upgrades/migrations.

I'll put together a fix for this shortly.

**Comment by cloudtracer** [comment]
Fixed in 2.0.20, should be available to upgrade in about an hour.

**Comment by hookhax** [comment]
Thanks for the quick fix here. Confirmed working now. Also appreciate the ZoomEye lookup. Good stuff!
