### ISSUE TITLE
AlienVault lookups never complete

### ISSUE THREAD

**Issue by deadbits** [cloudtracer/ThreatPinchLookup#77]
After adding my API key to the AlienVault looks up and the ThreatPinch Lookup extension tests the connection, the extension gets stuck on this screen seemingly indefinitely. Any thoughts?

**AlienVault Test within Extension**

<img width="1679" alt="Screen Shot 2019-04-04 at 11 30 05 AM" src="https://user-images.githubusercontent.com/1332757/55568235-54a69b00-56cd-11e9-8583-7d46051f863e.png">

**Comment by cloudtracer** [comment]
Hi @deadbits,

I did a few quick tests and wasn't able to reproduce this behavior.

The loader there almost looks like the loader for the Alienvault website, so I'm wondering if perhaps the service was down and the browser got some kind of redirect response.

Short answer, not sure.  Any chance you can provide some steps to reproduce this consistently?

**Comment by deadbits** [comment]
yeah, that’s definitely the alienvault loading screen.   
  
  

 I think this may be due to some browser extensions I’m using… I'll   test this out in another clean browser and see what happens.
  

  
It happened after a fresh install of Threat Pinch, then adding my API Key to the AlienVault MD5 lookup and hitting Next on that menu screen. Tried it several times throughout the day and same thing happened with all the AlienVault configurations.   
  

  
Again, very well might be by browser so I'll test a bit more and get back to this ticket today if it's still happening or just close it out if not.
  

  
Thanks for looking into this

**Comment by deadbits** [comment]
Yup looks like browser extensions I had enabled was blocking some AlienVault activity. Sorry it took me so long to respond to this. I'll close it out :) no fix needed, keep on rockin'
