### ISSUE TITLE
Cymon IP lookup default URL incorrect

### ISSUE THREAD

**Issue by deadbits** [cloudtracer/ThreatPinchLookup#78]
I'm setting up ThreatPinch on Chrome right now, and the default API URL's for Cymon is not longer used. They seem to have changed endpoints and the results you get back will be the homepage for instance.

I updated to this and it works fine: `https://cymon.io/api/nexus/v1/ip/${PINCH.HOVERITEM}/timeline`

**Comment by cloudtracer** [comment]
Very cool, thanks for letting me know. I'll try to get this fixed and updated this weekend.

**Comment by deadbits** [comment]
No problem, thank you!   
  
  
  
  
  
 --  
Adam M. Swanda
  

  
PGP: https://keybase.io/deadbits
  
  
  
  

  
  
>

**Comment by Dr-Flay** [comment]
Cymon was shut down at the end of April
https://github.com/hslatman/awesome-threat-intelligence/issues/159

**Comment by deadbits** [comment]
This thread is from 3 months ago. I'd say it's a non issue in the context of this ticket.

**Comment by deadbits** [comment]
Makes sense to open a new ticket or Pull Request to ask for the removal of Cymon, though.
